"""add field company_name_clearbit

Revision ID: 88a643401628
Revises: 9929f102924b
Create Date: 2024-03-24 20:04:16.262017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a643401628'
down_revision: Union[str, None] = '9929f102924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name_clearbit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name_clearbit')
    # ### end Alembic commands ###
