"""update referer 1

Revision ID: 9929f102924b
Revises: c4a2a9a2cb79
Create Date: 2024-03-21 17:03:36.780985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9929f102924b'
down_revision: Union[str, None] = 'c4a2a9a2cb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referer_cod', sa.String(), nullable=True))
    op.drop_constraint('users_referal_cod_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['referer_cod'])
    op.drop_column('users', 'referal_cod')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referal_cod', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_referal_cod_key', 'users', ['referal_cod'])
    op.drop_column('users', 'referer_cod')
    # ### end Alembic commands ###
