"""update referer 1

Revision ID: c4a2a9a2cb79
Revises: 32e437551532
Create Date: 2024-03-21 16:22:23.433425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a2a9a2cb79'
down_revision: Union[str, None] = '32e437551532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'referal_program', ['referal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referal_program', type_='unique')
    # ### end Alembic commands ###
