"""update add referer

Revision ID: dbbd8dddbe2b
Revises: 1afd43a013dc
Create Date: 2024-03-21 16:20:21.525498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbd8dddbe2b'
down_revision: Union[str, None] = '1afd43a013dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referal_program', sa.Column('referer_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referal_program', 'referer_user')
    # ### end Alembic commands ###
